vectornav:
  ros__parameters:
    # Defined in udev rules, change according to your system. Typically /dev/ttyUSB0
    serial_port: /dev/ttyUSB0

    # Acceptable baud rates : 9600, 19200, 38400, 57600, 115200, 230400, 460800, 921600
    # Datasheet states 128000 works but from experiments it does not.
    serial_baud: 921600

    # Enable set acc bias service
    acc_bias_enable: true

    # Time in seconds to take samples
    set_acc_bias_seconds: 5.0

    # Acceptable data rates in Hz: 1, 2, 4, 5, 10, 20, 25, 40, 50, 100, 200
    # Baud rate must be able to handle the data rate
    async_output_rate: 100

    # Acceptable imu rates in Hz: 1, 2, 4, 5, 10, 20, 25, 40, 50, 100, 200
    imu_output_rate: 100

    # Device IMU Rate as set by the manufacturer (800Hz unless specified otherwise)
    # This value is used to set the serial data packet rate
    fixed_imu_rate: 800

    # Use sensor timestamp instead of ROS timestamp to mitigate USB communication issues
    adjust_ros_timestamp: true

    # Data publication form:
    # - Both false for North East Down (IMU standard frame)
    # - tf_ned_to_enu: true for East North Up (Standard frame for robot_localization and other packages)
    # - tf_ned_to_nwu: true for North West Up (ROS standard frame, alligned with robot base link)
    tf_ned_to_enu: true
    tf_ned_to_nwu: false

    # If publishing ENU/NWU, do we want to publish in the frame labeled on the device? Default is false.
    # If tf_ned_to_enu = true and frame_based_enu = false orientation is reported by: x->y y->x z->-z to rotate the quaternion
    # If tf_ned_to_nwu = true and frame_based_nwu = false orientation is reported by: x->x y->-y z->-z to rotate the quaternion
    # Proper method is to rotate the quaternion by multiplication
    # If tf_ned_to_xxx = true and frame_based_xxx = true we rotate the quaternion to the frame matched label by multiplication
    # Please note that this has not been properly tested
    frame_based_enu: false
    frame_based_nwu: false

    # Number of consecutive invalid data packets allowed before shutting node down. Use -1 to deactivate this feature
    max_invalid_packets: 500

    # Make sure all covariances below are of type xx.xx , i.e. double so that the rpc is parsed correctly

    # Linear Acceleration Covariances not produced by the sensor
    linear_accel_covariance: [0.01,  0.0,    0.0,
                              0.0,   0.01,   0.0,
                              0.0,   0.0,    0.01]

    # Angular Velocity Covariances not produced by the sensor
    angular_vel_covariance: [0.005,  0.0,    0.0,
                             0.0,    0.005,  0.0,
                             0.0,    0.0,    0.005]

    # Orientation covariance overwritten in driver, this is unused in the code
    orientation_covariance: [0.01,  0.0,   0.0,
                             0.0,   0.01,  0.0,
                             0.0,   0.0,   0.01]

    # Commands IMU firmware to change its reference frame. (1.0, 1.0, 1.0) is NED.
    # Use identity matrix along with tf_ned_to_nwu if IMU is mounted in the standard position
    # Avoid changing this param if possible and use tf_ned_to_xxx if possible
    # We kept this param to be able to reset already modified IMU frames
    rotation_reference_frame: [1.0,  0.0,  0.0,
                               0.0,  1.0,  0.0,
                               0.0,  0.0,  1.0]
