joystick_node:
  ros__parameters:
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.0
    scale_angular_turbo:
      yaw: 1.0

    enable_button: 5 # RB shoulder button
    enable_turbo_button: 4  # LB shoulder button
