joystick_node:
  ros__parameters:
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_twist_joy_node:
  ros__parameters:
    publish_stamped_twist: true

    axis_linear:
      x: 1
    scale_linear:
      x: 1.0
    scale_linear_turbo:
      x: 2.0

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 10.0
    scale_angular_turbo:
      yaw: 20.0

    enable_button: 5 # R1 shoulder button
    enable_turbo_button: 4  # L1 shoulder button
